src/Collections/Collections.Web/Controllers/TagController.cs
using Collections.ApplicationCore.Models;
using Collections.ApplicationCore.Specifications;
using Collections.Shared.Interfaces;
using Collections.Web.Models.Items;
using Collections.Web.Models.Tags;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Web.Controllers;

public class TagController : Controller
{
    private readonly IReadRepository<Tag> _tagReadRepository;

    // GET
    public TagController(IReadRepository<Tag> tagReadRepository)
    {
        _tagReadRepository = tagReadRepository;
    }

    public async Task<IActionResult> Index(int id)
    {
        var specification = new TagByIdSpec(id);
        var tagVm = await _tagReadRepository.GetBySpecProjectedAsync<TagViewModel>(specification);
        return View(tagVm);
    }
}

src/Collections/Collections.Web/Controllers/UserProfileController.cs
using Collections.ApplicationCore.Models;
using Collections.ApplicationCore.Specifications;
using Collections.Shared.Constants.Filtering;
using Collections.Shared.Interfaces;
using Collections.Web.Filters;
using Collections.Web.Models;
using Collections.Web.Models.UserProfile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Web.Controllers;

[Authorize]
public class UserProfileController : Controller
{
    private readonly IReadRepository<UserProfile> _userProfileReadRepository;

    public UserProfileController(IReadRepository<UserProfile> userProfileReadRepository)
    {
        _userProfileReadRepository = userProfileReadRepository;
    }

    [AllowAnonymous]
    public async Task<IActionResult> Details(int id)
    {
        var profileSpec = new UserProfileByIdSpec(id);
        var profileViewModel = await _userProfileReadRepository.GetBySpecProjectedAsync<UserProfileViewModel>(profileSpec);
        return View(profileViewModel);
    }
}

src/Collections/Collections.Web/Views/Shared/_CollectionCard.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Markdig
@model Collections.Web.Models.Collection.CollectionViewModel
@inject IViewLocalizer ViewLocalizer

<div class="col">
    <div class="card shadow-sm">
        @{
            if (@Model.ImageName != null)
            {
                <img class="card-img-top cropped" focusable="false" src="@Model.ImageSource" />
            }
            else
            {
                <img class="card-img-top cropped" focusable="false" src="~/img/placeholder.jpg" />
            }
        }
        <div class="card-body">
            <p class="card-text">
                @Model.Title 
                <a asp-action="Details" asp-controller="UserProfile" asp-route-id="@Model.UserProfileId" class="text-decoration-none"><small class="text-muted">@ViewLocalizer["By"] @Model.ProfileFullName</small></a>
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a asp-controller="Collections" asp-action="Details" asp-route-id=@Model.Id type="button" class="btn btn-sm btn-outline-secondary p-2">
                        @ViewLocalizer["See details"]
                    </a>
                    <a type="button" class="btn btn-outline-secondary" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-html="true" title="@Html.Raw(Markdown.ToHtml(@Model.Description))">
                        <i class="bi bi-patch-question"></i>
                    </a>
                </div>
                <small class="text-muted"><i class="bi bi-files"></i> @Model.ItemsCount</small>
            </div>
        </div>
    </div>
</div>

src/Collections/Collections.Web/Views/Shared/_CultureDropdown.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Collections.Web.Interfaces
@inject ILocalisationOptionsProvider Options

@{
    var options = Options.GetOptions();
    var culture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = options.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : 
        $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div class="me-2">
    <form asp-action="SetCulture" asp-controller="Home" asp-route-returnUrl="@returnUrl">
        <select id="culture" name="culture" asp-for="@culture.RequestCulture.UICulture.Name"
                asp-items="@cultures" onchange="this.form.submit();"></select>
    </form>
</div>

src/Collections/Collections.Web/Views/Shared/_ItemCard.cshtml
@model Collections.Web.Models.Items.CardItemViewModel

<div class="col">
    <div class="card shadow-sm">
        <div class="card-header">
            @Model.Title
        </div>
        <div class="card-body">
            @if (Model.Tags.Any())
            {
                <div class="p-1 mb-3 d-flex">
                    @foreach (var tag in Model.Tags)
                    {
                        <a class="text-decoration-none text-white badge bg-success text-decoration-none me-1" asp-action="Index" asp-controller="Tag" asp-route-id="@tag.Id">@tag.Text</a>
                    }
                </div>
            }
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a asp-controller="Item" asp-action="Details" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">@ViewLocalizer["See details"]</a>
                </div>
                <div class="d-flex">
                    <div class="d-flex text-primary me-2">
                        <i class="bi bi-chat-right-text me-1"></i>
                        <small>@Model.CommentsCount</small>
                    </div>
                    <div class="d-flex text-danger">
                        <i class="bi bi-heart me-1"></i>
                        <small>@Model.LikesCount</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Collections/Collections.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Collections</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Collections.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Collections</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
            <partial name="_LoginPartial"/>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Collections
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Collections/Collections.Web/Views/Shared/_ThemeDropdown.cshtml
@{
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : 
        $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<div class="me-2">
    <form asp-action="SetTheme" asp-controller="Home" asp-route-returnUrl="@returnUrl">
        <select id="theme" name="theme" asp-for="@Context.Request.Cookies["theme"]" onchange="this.form.submit();">
            <option value="light">Light</option>
            <option value="dark">Dark</option>
        </select>
    </form>
</div>